version: '2'

services:
  traefik:
    image: traefik
    restart: unless-stopped
#    command: -c /dev/null --web --docker --logLevel=DEBUG
    command: -c /dev/null --web --docker --logLevel=INFO --defaultEntryPoints='https' --entryPoints="Name:https Address::443 TLS:/certs/cert.pem,/certs/key.pem" --entryPoints="Name:http Address::80 Redirect.EntryPoint:https"
    networks:
      - d8
      - d7
      - main
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - ./certs:/certs/
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  main:
    external:
      name: main_default
  d8:
    external:
      name: d8_default
  d7:
    external:
      name: d7_default
